name: wzpdcl_app_flutter
description: A ADN diginet project

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  # The following adds the Cupertino Icons fonts to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.22.0
  http: ^0.13.3
  webview_flutter: ^2.0.10
  webview_flutter_plus: ^0.2.3+1
  flutter_webview_plugin: ^0.4.0
  rflutter_alert: ^2.0.4
  linked_scroll_controller: ^0.2.0
  google_maps_flutter: ^2.0.6
  geolocator: ^7.3.1
  flutter_geocoder: ^0.2.2-nullsafety
  fluttertoast: ^8.0.8
  url_launcher: ^6.0.17
  horizontal_data_table: ^3.6.0
 ## rapidfire: ^0.0.1-alpha.6.0
  shared_preferences: ^2.0.7
  dio: ^4.0.1
  flutter_phone_direct_caller: ^2.1.0
  syncfusion_flutter_pdfviewer: ^19.4.38-beta
  flutter_email_sender: ^5.0.2
  share: ^2.0.4
  launch_review: ^3.0.1
  ##flutter_document_picker: ^4.0.1
  flutter_document_picker: ^5.0.1-nullsafety.0
  image_picker: ^0.8.3+3
  gsheets: ^0.3.2
  marquee: ^2.2.0

  ##progress_dialog: ^1.2.4
  ##http_middleware: ^1.0.0
  ##http_logger: ^1.0.0
    #bar chart implementation
    #charts_flutter: ^0.11.0
  charts_flutter:
    git:
      url: https://github.com/google/charts
      path: charts_flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  ##build_runner: ^2.0.6
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons fonts is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - assets/webpages/
    - assets/images/development.jpg
    - assets/vectors/
    - assets/vectors/nav_menu/
    - assets/vectors/guests/
  # To add assets to your application, add an assets section, like this:


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the fonts family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the fonts. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  fonts:
    - family: siyamrupali
      fonts:
        - asset: assets/fonts/siyamrupali.ttf
        - asset: assets/fonts/siyamrupali.ttf

    - family: android
      fonts:
        - asset: assets/fonts/android.ttf

    - family: android2
      fonts:
        - asset: assets/fonts/android2.ttf

